import Document, { Html, Head, Main, NextScript } from 'next/document'
import 'twin.macro'

class MyDocument extends Document {
  render() {
    return (
      <Html lang="en" tw="overflow-hidden h-full">
        <Head>
          <link
            href="/fonts/Poppins/poppins-v15-latin-100.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            href="/fonts/Poppins/poppins-v15-latin-100italic.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            rel="preload"
            href="/fonts/Poppins/poppins-v15-latin-200.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            href="/fonts/Poppins/poppins-v15-latin-200italic.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            href="/fonts/Poppins/poppins-v15-latin-300.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            href="/fonts/Poppins/poppins-v15-latin-300italic.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            rel="preload"
            href="/fonts/Poppins/poppins-v15-latin-regular.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            href="/fonts/Poppins/poppins-v15-latin-italic.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            href="/fonts/Poppins/poppins-v15-latin-500.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            href="/fonts/Poppins/poppins-v15-latin-500italic.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            href="/fonts/Poppins/poppins-v15-latin-600.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            href="/fonts/Poppins/poppins-v15-latin-600italic.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            href="/fonts/Poppins/poppins-v15-latin-700.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            href="/fonts/Poppins/poppins-v15-latin-700italic.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            href="/fonts/Poppins/poppins-v15-latin-800.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            href="/fonts/Poppins/poppins-v15-latin-800italic.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            href="/fonts/Poppins/poppins-v15-latin-900.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            href="/fonts/Poppins/poppins-v15-latin-900italic.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            rel="preload"
            href="/fonts/Work_Sans/work-sans-variableFont_wght-subset.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
          <link
            href="/fonts/Work_Sans/work-sans-italic-variableFont_wght-subset.woff2"
            as="font"
            type="font/woff2"
            crossOrigin=""
          />
        </Head>
        <body tw="bg-gradient-to-b from-orange-50 to-orange-100 font-body overflow-auto h-full">
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument
